const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCYHvaiqXBQgBkPH2Q8ZF55w25c
kpl5nLZzyb4/wIWuvAESwX88pY+m+IJHQR1DC5j5HOLc/MDZGKIfijyiYAsy+1om
MlneNHjSihyyrA+3L42EOJ/TFrAh977ys+eHyB5YqJQtGPaiAqxUL2c1NXV2lfun
WZKyprdzcdsKAS5XLQIDAQAB
-----END PUBLIC KEY-----`

module.exports = PUBLIC_KEY